name: mac_desktop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  http: ^1.3.0
  ollama: ^1.0.4
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
